Add a data mask to SSN and ITIN input fields
codeforamerica/vita-min pull request #1884
Opened 2021-12-03 18:25 UTC by caitbot

Adds a javascript plugin to allow data-masking on fields, which adds hyphens into the field as you type.

For [this story](https://www.pivotaltracker.com/story/show/179062568)

2021-12-03 19:17 UTC, bytheway875 commented
I _think_ there's something built into honeycrisp that will do this as well, but I honestly prefer us relying on whatever the popular JS implementation is for this at the moment because I know people had talked about the honeycrisp one being kind of wonky.

2021-12-03 23:00 UTC, embarnard requested changes
Looks good! But looks like a test is failing at spec/features/ctc/portal_spec.rb:254 and giving a validation error that the SSN or ITIN field "Can't be blank".

2021-12-06 18:48 UTC, embarnard approved these changes
Woohoo!! 😊

2021-12-06 18:48 UTC, embarnard commented on app/forms/ctc/base_spouse_form.rb
> +    before_validation { spouse_ssn&.remove!("-") }
looks good!

2021-12-07 15:46 UTC, bytheway875 commented on app/forms/ctc/base_primary_filer_form.rb
> +    before_validation do
I feel like we're going to want to make sure this is consistent across all implementations of SSN persistance. Maybe we can have the SSN/ITIN validator handle scrubbing when validating, and then add the removal to the before_save on intake when these fields are present. 

(I also thought that when we discussed length of 11 SSN fields, Travis said that this scrubbing was already being done somewhere consistently to ensure only numbers got into the DB?)

2021-12-14 17:26 UTC, merged