Add IRS language preference page
codeforamerica/vita-min pull request #2847
Opened 2022-06-17 22:52 UTC by embarnard

2022-06-21 16:06 UTC, alaroia-cfa reviewed
One blocker and a handful of comments. Good code overall!

2022-06-21 20:03 UTC, embarnard commented on app/helpers/irs_languages.rb
> +
add comment, this is to add spanish as default

2022-06-21 20:05 UTC, embarnard commented on app/views/ctc/questions/irs_language_preference/edit.html.erb
> +    <%= f.cfa_select(:irs_language_preference, t("views.ctc.questions.irs_language_preference.select_language"), IrsLanguages.display_values(locale)) %>
Add value in select_options to select default

2022-06-22 14:51 UTC, alaroia-cfa approved these changes
I approve. I'd prefer to see a handful of changes implemented per follow-up comments; you may merge with or without those changes. I strongly encourage doing them.

This code is now simple! Great work.

Happy to Tuple to implement/discuss the suggestions together.

2022-06-22 14:51 UTC, alaroia-cfa commented on spec/controllers/ctc/questions/irs_language_preference_controller_spec.rb
> +    context "locale is es and irs_language_preference is nil" do
I suggest creating a:

`context "without a saved language preference" do`

and moving these two tests into it.

2022-06-22 14:51 UTC, alaroia-cfa commented on spec/controllers/ctc/questions/irs_language_preference_controller_spec.rb
> +      it "Spanish is selected" do
I suggest `it "selects Spanish by default"` so that it flows like an English sentence.

2022-06-22 14:51 UTC, alaroia-cfa commented on spec/controllers/ctc/questions/irs_language_preference_controller_spec.rb
> +      it "English is selected" do
It would be nice to make this flow like an English sentence, too.

2022-06-22 14:51 UTC, alaroia-cfa commented on spec/controllers/ctc/questions/irs_language_preference_controller_spec.rb
> +    context "irs_language_preference is russian" do
Maybe this could be:

```
context "with a saved language preference" do
```

2022-06-22 14:51 UTC, alaroia-cfa commented on spec/controllers/ctc/questions/irs_language_preference_controller_spec.rb
> +      it "Russian is selected" do
It would be nice to make this flow like an English sentence, too.

2022-06-22 17:10 UTC, alaroia-cfa commented on spec/controllers/ctc/questions/irs_language_preference_controller_spec.rb
> +      it "Spanish is selected" do
Per Tuple conversation, it reads OK when you see the whole RSpec test in context, but we still ended up changing it.

2022-06-22 18:23 UTC, bytheway875 commented
@alaroia-cfa @embarnard FYI, as implemented this will begin attaching the ScheduleLEP to EVERY return, once merged.

I think we need to update the logic for when this gets attached in the `supported_documents` method in submission_builder/ty2021/return1040.rb before merging this. (The original implementation assumed we would be asking people a second question of whether they wanted to change their preference, and would only save a value if they said yes).


![Screen Shot 2022-06-22 at 11 19 38 AM](https://user-images.githubusercontent.com/4494389/175109004-2fe50a8a-c15d-415e-bd54-cafc85e3371a.png)

2022-06-22 18:24 UTC, bytheway875 requested changes
I think we need to make sure to only attach this to returns where the preference either a) has changed from previous year (probably impossible without asking another intake question) or b) has a value other than english, instead of right now the logic is "any value at all". See other comment!

2022-06-22 18:26 UTC, alaroia-cfa commented
@bytheway875 Oh! I didn't realize it would have that effect. Good catch.

I'm seeing that there's a `.present?` check. @embarnard , what if we allowed "No preference" as an option in the list? I haven't gone and checked design's mocks to see if they have an opinion on how to handle this.

I'm in theory happy to pair but actually it's subject to my calendar. Maybe I'll call you Em to connect later, but feel free to do whatever is reasonable without me too.

2022-06-22 20:06 UTC, merged