Remove getting started message, change message copy for `successful_submission_online_intake`
codeforamerica/vita-min pull request #3350
Opened 2023-01-23 19:31 UTC by embarnard

2023-01-24 18:01 UTC, embarnard commented
Update the `successful_submission_online_intake` message. This is the new copy below.
![Screen Shot 2023-01-24 at 12 59 05 PM](https://user-images.githubusercontent.com/49880002/214371556-a8eedda8-79b5-4dc4-9152-3edbf01b3fcd.png)

And this is the old copy:
![Screen Shot 2023-01-24 at 1 00 16 PM](https://user-images.githubusercontent.com/49880002/214371749-e6de7c82-cc96-4612-930f-c281fbae29a3.png)

This story also removes the getting_started message. Originally we were going to change/add back in the in_progress message but now its going to be a different message and included in another ticket.

2023-01-25 18:05 UTC, alaroia-cfa requested changes
See comments for two blocking requests to confirm copy.

See other comments for some non-blocking questions/comments.

Happy to chat more!

2023-01-25 18:05 UTC, alaroia-cfa commented on config/locales/en.yml
> +        Hello <<Client.PreferredName>>, Your tax information was successfully submitted to GetYourRefund**.** IMPORTANT**:** Your Client ID is <<Client.ClientId>>. Please keep track of this number an
In terms of English punctuation/spacing, I think this should be `**IMPORTANT**` not `** IMPORTANT**`.

However, are you sure program/product wants these asterisks here? I don't see them in the Notion doc.

2023-01-25 18:10 UTC, embarnard commented on config/locales/en.yml
> +        subject: Welcome to GetYourRefund/ Client ID
@alaroia-cfa I didn't mean to have that difference `/` vs `:` so I'll change it to the colon. Thanks for the thorough review!

2023-01-25 21:37 UTC, merged