TBE-28 Allow transitioning intakes to all possible states when not in production
codeforamerica/vita-min pull request #4636
Opened 2024-07-09 16:42 UTC by tofarr

## [TBE-28](https://codeforamerica.atlassian.net/browse/TBE-28)
## Is PM acceptance required?
- [X] Yes - don't merge until JIRA issue is accepted!
## What was done?
- Refactored all the transition code into a single location
- When not in production, state file admin users are permitted to transition an intake into any permitted next state.
- Mention any relevant issues or insights to be shared with the reviewer.
- Alternatives considered
## How to test?
- Describe the testing approach taken to verify the changes, including:
  - Unit/integration/manual tests
  - Test data used
- Specify any relevant testing environments used (e.g., development, staging, demo, Heroku).
- Risk Assessment
  - Risks or side effects associated with the changes and how they were mitigated.
  - Highlight areas that may need extra attention during code review or testing.
  - Paste SQL queries or output where relevant
## Screenshots (for visual changes)
- Before
- After

2024-07-09 17:51 UTC, tofarr commented on app/controllers/hub/efile_submissions_controller.rb
> +      if @efile_submission.transition_to!(to_state, { initiated_by_id: current_user.id })
lets attach an error code here if possible too

2024-07-10 15:19 UTC, embarnard requested changes
This all looks great! I think like we were talking before I would prefer there to be some sort of artificial efile error attached to rejected and failed transitions since it will be what matches what happens in the poll for acknowledgment service and since last season it was critical that we had these errors attached for testing.

in the old code we did something like this
`@efile_submission.transition_to!(:rejected, error_code: EfileError.where(service_type: :state_file).last.code)`

2024-07-12 16:18 UTC, embarnard approved these changes

2024-07-12 16:18 UTC, embarnard commented on app/controllers/hub/state_file/efile_submissions_controller.rb
> +        if to_state == "rejected"
Looks great! thanks for making that change

2024-07-24 16:47 UTC, merged