FYST-784 Create basic DF intakes for ID
codeforamerica/vita-min pull request #4821
Opened 2024-10-02 18:10 UTC by tahsinaislam

## Link to pivotal/JIRA issue
https://codeforamerica.atlassian.net/browse/FYST-784

## Is PM acceptance required? (delete one)
- Yes - don't merge until JIRA issue is accepted!

## What was done?
- Explain the implementation goals being solved or the feature with the reviewer in mind
- Mention any relevant issues or insights to be shared with the reviewer.
- Alternatives considered
## How to test?
- Describe the testing approach taken to verify the changes, including:
  - Unit/integration/manual tests
  - Test data used
- Specify any relevant testing environments used (e.g., development, staging, demo, Heroku).
- Risk Assessment
  - Risks or side effects associated with the changes and how they were mitigated.
  - Highlight areas that may need extra attention during code review or testing.
  - Paste SQL queries or output where relevant
## Screenshots (for visual changes)
- Before
- After

2024-10-02 22:11 UTC, jenny-heath approved these changes
obviously i did not read the xml lol but i see that they live in the right place and look valid 👌

2024-10-02 22:26 UTC, mpidcock requested changes

2024-10-02 22:26 UTC, mpidcock commented on spec/fixtures/state_file/fed_return_xmls/2023/nc/cookiemonster.xml
> +    <TaxYr>2023</TaxYr>
Can you apply this change to nick and spiderman? I think we should go ahead and make that update

2024-10-03 15:33 UTC, mpidcock approved these changes

2024-10-03 16:15 UTC, mpidcock approved these changes

2024-10-03 16:16 UTC, merged