Update state information service
codeforamerica/vita-min pull request #5139
Opened 2024-12-06 21:31 UTC by squanto

## Link to pivotal/JIRA issue
- https://codeforamerica.atlassian.net/browse/FYST-1392

## Is PM acceptance required? (delete one)
- Yes - don't merge until JIRA issue is accepted!

**Reminder**: merge main into this branch and get green tests before merging to main
## What was done?
- Update `StateInformationService` values for 2024

2024-12-06 23:19 UTC, embarnard commented on app/services/state_file/state_information_service.rb
> +        mail_voucher_address: "Idaho State Tax Commission<br/>" \
I see that is getting called on the return status page, we never show the addresses in Spanish right? I don't think we do but might want to check in with product on that if they haven't already said something

2024-12-06 23:20 UTC, embarnard approved these changes
Looks good! Just had a question but if it seems good to you feel free to proceed

2024-12-12 01:27 UTC, mpidcock requested changes
Looks like there were some details missing from the jira ticket so some minor fixes need to be made

2024-12-12 01:27 UTC, mpidcock commented on app/lib/pdfs/ID-VP.pdf
Since this pdf is used for a public link, we need to store it under `public/pdfs`

2024-12-12 01:27 UTC, mpidcock commented on app/services/state_file/state_information_service.rb
>          voucher_path: "",
We'll also need to add the MD voucher pdf and set the path here

2024-12-12 01:27 UTC, mpidcock commented on app/services/state_file/state_information_service.rb
> +        department_of_taxation: "https://www.ncdor.gov/",
This was a mistake in the jira ticket - the value should be the name of the Department (North Carolina Department of Revenue)

2024-12-13 20:53 UTC, mpidcock approved these changes

2024-12-13 20:53 UTC, mpidcock commented on app/services/state_file/state_information_service.rb
>          voucher_path: "",
We can follow up on this later

2024-12-16 21:44 UTC, merged